### ISSUE TITLE
doesn't worked 

### ISSUE THREAD

**Issue by ArtemGuy** [FGonzalezLopez/NPI_15_16_Kinect#1]
That's program shows me the Spanish text that I'm out of range :(

**Comment by FGonzalezLopez** [comment]
I honestly wasn't expecting anybody to reach out for this :0. 

I'm guessing you are referring to the 
`//this.outOfPlaceWarn.Text = "Estás fuera de la zona de actividad.\nPor favor, aléjate con las manos encima de\nla cabeza hasta que quepan cómodamente\nen la pantalla para ser reconocido";` line, (which I suppose you have uncommented to make the prompt appear on screen)
within the pushPromptToReposition() method. I'm sorry for the language, I intended to write all the prompts in English but I decided not to, as it was a university project.

To "start" the program, you have to stand far enough from the Kinect so you can see your full body, with your arms up slightly above your head, and only then will it display the user interface and let you choose an exercise.

Please do ask for further help if you need it, I'm more than happy to try to help you.

**Comment by ArtemGuy** [comment]
Thak you so much! It's works! But i want to khow, what is the meaning of this project? It keeps track of the human skeleton, and for which there is a house and arrows?

**Comment by FGonzalezLopez** [comment]
Well its main objective was to learn how to use the Kinect API to create a user interface controlled by the user's body, so it is not polished towards serving any actual purpose. It consists of a menu (the home and the arrows), left and right arrows to select an exercise, up arrow to execute the routine for the selected exercise, and the house is to go back to the menu. 

There are only 3 exercises, I don't recall the specifics about any of them but they all involve moving your hands towards the marks till they are green, going back to a standstill position, and then repeating a few times (as many times as the box for the repetitions has stored). One of them involved raising your hands above your head, another keeping your arms in a certain position for 2 or 3 seconds, and the last one I can't really remember, although something similar.

**Comment by ArtemGuy** [comment]
Okay, that's cool! You're well done!
